[workspace]
authors = ["Elia Cereda <eliacereda@gmail.com>"]
channels = ["robostack-staging", "conda-forge"]
name = "robotics-lab-usi-robomaster"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]
build-variants = { python = ["3.12.*"] }

[tasks]

[dependencies]
# ROS2 Humble
python = ">=3.12.13,<3.13"
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
compilers = ">=1.11.0,<2"
make = ">=4.4.1,<5"

# CoppeliaSim dependencies
cbor2 = ">=6.1.1,<7"
pyzmq = ">=27.1.0,<28"

# robomaster_sim dependencies
spdlog = ">=1.17.0,<2"
libboost = ">=1.88.0,<2"
cmake = ">=4.2.3,<5"
ffmpeg = ">=8.1.1,<9"
libxslt = ">=1.1.43,<2"
xmlschema = ">=4.3.1,<5"

# robomaster_ros dependencies
ros-humble-xacro = ">=2.1.1,<3"
ros-humble-launch-xml = ">=1.0.14,<2"
ros-humble-cv-bridge = ">=3.2.1,<4"
ros-humble-launch-testing-ament-cmake = ">=1.0.14,<2"
ros-humble-robot-state-publisher = ">=3.0.3,<4"
ros-humble-joint-state-publisher = ">=2.4.0,<3"
ros-humble-joint-state-publisher-gui = ">=2.4.0,<3"
ros-humble-joy = ">=3.3.0,<4"
ros-humble-joy-teleop = ">=1.7.0,<2"

# robomaster_example dependencies
transforms3d = ">=0.4.2,<0.5"

# RoboMaster-SDK
rm_libmedia_codec = { path = "src/RoboMaster-SDK/lib/libmedia_codec" }

[pypi-dependencies]
# RoboMaster-SDK
robomaster = { path = "src/RoboMaster-SDK", editable = true }

# robomaster_ros dependencies
numpy-quaternion = ">=2024.0.13, <2025"

[activation]
scripts = ["install/setup.sh"]

[activation.env]
ROS_LOCALHOST_ONLY = "1"

COPPELIASIM_ROOT_DIR = "/Applications/coppeliaSim.app/Contents/Resources"

# CMake toolchain file to use only Pixi libraries in the build process
CMAKE_TOOLCHAIN_FILE = "$PIXI_PROJECT_ROOT/pixi-toolchain.cmake"

[target.osx-64.tasks]
coppelia = "$COPPELIASIM_ROOT_DIR/../MacOS/coppeliaSim"

[target.osx-arm64.tasks]
coppelia = "$COPPELIASIM_ROOT_DIR/../MacOS/coppeliaSim"

[target.linux-64.tasks]
coppelia = "$COPPELIASIM_ROOT_DIR/coppeliaSim.sh"
